import UserImage from "../assets/images/avatar.png";

const projectInfo = {
  entityMap: {},
  blocks: [
    {
      key: "7u1uf",
      text: "Vidly Front-end:",
      type: "header-one",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "c6ip",
      text: "",
      type: "header-one",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "6ljf3",
      text: "Overview:",
      type: "header-four",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "d64gk",
      text:
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, aliquam? ",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "8ja4f",
      text:
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, aliquam? ",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "dl247",
      text:
        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, aliquam?",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "312l7",
      text: "",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "7t78t",
      text: "as",
      type: "unordered-list-item",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "24jic",
      text: "ds",
      type: "unordered-list-item",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: "9pg0b",
      text: "sd",
      type: "unordered-list-item",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
  ],
};

let data = {
  name: "Michal",
  reminders: [
    { id: 1, title: "Upload Vidly to GitHub" },
    { id: 2, title: "Meeting w/ Martin @14:30" },
    { id: 3, title: "Change setState func in Vidly" },
  ],
  activity: [
    { date: new Date(2020, 1, 5), changes: 5 },
    { date: new Date(2020, 2, 5), changes: 6 },
    { date: new Date(2020, 3, 5), changes: 3 },
    { date: new Date(2020, 4, 5), changes: 0 },
    { date: new Date(2020, 5, 5), changes: 1 },
    { date: new Date(2020, 6, 5), changes: 0 },
    { date: new Date(2020, 7, 5), changes: 3 },
    { date: new Date(2020, 8, 5), changes: 4 },
    { date: new Date(2020, 9, 5), changes: 2 },
    { date: new Date(2020, 10, 5), changes: 0 },
    { date: new Date(2020, 11, 5), changes: 4 },
    { date: new Date(2020, 12, 5), changes: 5 },
    { date: new Date(2020, 13, 5), changes: 2 },
    { date: new Date(2020, 14, 5), changes: 1 },
  ],
  projects: [
    {
      title: "test1",
      description: "lorem",
      id: 1,
      content: projectInfo,
      isPrioritized: true,
      daysSinceUpdate: 3,
      status: "inProgress",
      IsLiked: false,
      shared: [123, 123, 123],
      tasks: [
        {
          id: 1,
          idParent: 1,
          title: "Vidly",
          isPrioritized: true,
          status: "inProgress",
          completion: 100,
          steps: [
            {
              id: 1,
              name: "Upload to GitHub",
              status: "Finished",
            },
            {
              id: 2,
              name: "Add deleted projects screen",
              status: "inProgress",
            },
            {
              id: 3,
              name: "Set up Heroku",
              status: "Finished",
            },
          ],
        },
        {
          id: 2,
          idParent: 1,
          title: "Vidly2",
          isPrioritized: false,
          completion: 20,
          status: "inProgress",
          steps: [
            {
              id: 1,
              name: "Upload to GitHub",
              status: "Finished",
            },
            {
              id: 2,
              name: "Add deleted projects screen",
              status: "inProgress",
            },
            {
              id: 3,
              name: "Set up Heroku",
              status: "Finished",
            },
          ],
        },
      ],
    },
    {
      title: "test2",
      description: "lorem",
      id: 2,
      content: projectInfo,
      isPrioritized: true,
      status: "Finished",
      daysSinceUpdate: 3,
      IsLiked: false,
      shared: [123, 123, 123],
      tasks: [
        {
          id: 3,
          idParent: 2,
          completion: 80,
          title: "Vidly",
          isPrioritized: false,
          status: "inProgress",
          steps: [
            {
              id: 1,
              name: "Upload to GitHub",
              status: "Finished",
            },
            {
              id: 2,
              name: "Add deleted projects screen",
              status: "inProgress",
            },
            {
              id: 3,
              name: "Set up Heroku",
              status: "Finished",
            },
          ],
        },
        {
          id: 4,
          idParent: 2,
          title: "Vidly2",
          isPrioritized: true,
          completion: 0,
          status: "behindSchedule",
          steps: [
            {
              id: 1,
              name: "Upload to GitHub",
              status: "Finished",
            },
            {
              id: 2,
              name: "Add deleted projects screen",
              status: "inProgress",
            },
            {
              id: 3,
              name: "Set up Heroku",
              status: "Finished",
            },
          ],
        },
      ],
    },
    {
      title: "test3",
      description: "lorem",
      daysSinceUpdate: 3,
      isPrioritized: false,
      id: 3,
      content: projectInfo,
      status: "inProgress",
      IsLiked: false,
      shared: [123, 123, 123, 123],
      tasks: [
        {
          id: 5,
          idParent: 3,
          completion: 5,
          isPrioritized: false,
          title: "Vidly",
          status: "toDo",
          steps: [
            {
              id: 1,
              name: "Upload to GitHub",
              status: "Finished",
            },
            {
              id: 2,
              name: "Add deleted projects screen",
              status: "inProgress",
            },
            {
              id: 3,
              name: "Set up Heroku",
              status: "Finished",
            },
          ],
        },
      ],
    },
    {
      title: "test4",
      description: "lorem",
      isPrioritized: false,
      daysSinceUpdate: 2,
      shared: [123, 123],
      content: projectInfo,
      id: 4,
      status: "Finished",
      IsLiked: false,
      tasks: [
        {
          id: 6,
          idParent: 4,
          title: "Vidly",
          isPrioritized: true,
          completion: 90,
          status: "inProgress",
          steps: [
            {
              id: 1,
              name: "Upload to GitHub",
              status: "Finished",
            },
            {
              id: 2,
              name: "Add deleted projects screen",
              status: "inProgress",
            },
            {
              id: 3,
              name: "Set up Heroku",
              status: "Finished",
            },
          ],
        },
        {
          id: 7,
          idParent: 4,
          title: "Vidly2",
          isPrioritized: true,
          completion: 0,
          status: "toDo",
          steps: [
            {
              id: 1,
              name: "Upload to GitHub",
              status: "Finished",
            },
          ],
        },
      ],
    },
    {
      title: "test5",
      description: "lorem",
      daysSinceUpdate: 6,
      shared: [123],
      isPrioritized: true,
      id: 5,
      content: projectInfo,
      status: "behindSchedule",
      IsLiked: false,
      tasks: [],
    },
    {
      title: "test6",
      description: "lorem",
      id: 6,
      status: "behindSchedule",
      content: projectInfo,
      shared: [],
      IsLiked: false,
      isPrioritized: false,
      tasks: [],
    },
    {
      title: "test7",
      description: "lorem",
      daysSinceUpdate: 1,
      id: 7,
      status: "Finished",
      content: projectInfo,
      shared: [],
      isPrioritized: false,
      IsLiked: false,
      tasks: [],
    },
    {
      title: "test8",
      description: "lorem",
      id: 8,
      status: "Finished",
      content: projectInfo,
      isPrioritized: true,
      shared: [],
      IsLiked: false,
      daysSinceUpdate: 2,
      tasks: [
        {
          id: 8,
          idParent: 8,
          title: "Vidly",
          completion: 100,
          status: "Finished",
          steps: [
            {
              id: 1,
              name: "Upload to GitHub",
              status: "Finished",
            },
            {
              id: 2,
              name: "Add deleted projects screen",
              status: "inProgress",
            },
            {
              id: 3,
              name: "Set up Heroku",
              status: "Finished",
            },
          ],
        },
        {
          id: 9,
          idParent: 8,
          title: "Vidly2",
          status: "inProgress",
          completion: 25,
          steps: [
            {
              id: 1,
              name: "Upload to GitHub",
              status: "Finished",
            },
            {
              id: 2,
              name: "Add deleted projects screen",
              status: "inProgress",
            },
            {
              id: 3,
              name: "Set up Heroku",
              status: "Finished",
            },
          ],
        },
      ],
    },
    {
      title: "test9",
      description: "lorem",
      isPrioritized: true,
      daysSinceUpdate: 3,
      id: 9,
      status: "inProgress",
      shared: [],
      IsLiked: false,
      tasks: [],
      content: projectInfo,
    },
  ],
  image: UserImage,
};

export default data;
